"""
Django settings for restaurant project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import ssl
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def _env(key: str, default: str = "") -> str:
    value = os.getenv(key, default).strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
        value = value[1:-1].strip()
    return value


# Quick-start development settings - unsuitable for production
SECRET_KEY = _env(
    "SECRET_KEY",
    "django-insecure-8-y9kuo=v+wl-c0d3@ta2wgr$*ek@5gl#07zp02b7568#=gn-g",
)
DEBUG = _env("DEBUG", "True").lower() in ("1", "true", "yes")
ALLOWED_HOSTS = [
    h.strip()
    for h in _env("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # Local apps
    'accounts',
    'menu',
    'orders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restaurant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restaurant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


def _normalize_pem(pem: str) -> str:
    return pem.replace("\\n", "\n").strip() + "\n"


def _pem_is_usable(pem: str) -> bool:
    """True only if OpenSSL can parse the certificate (avoids PyMySQL cafile errors)."""
    if "-----BEGIN CERTIFICATE-----" not in pem or "-----END CERTIFICATE-----" not in pem:
        return False
    try:
        ssl.create_default_context(cadata=_normalize_pem(pem))
        return True
    except ssl.SSLError:
        return False


def _ssl_context_from_pem(pem: str) -> ssl.SSLContext:
    return ssl.create_default_context(cadata=_normalize_pem(pem))


def _read_pem_file(path: Path) -> str | None:
    if not path.is_file():
        return None
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return None


def _ssl_options_without_verification() -> dict:
    """Encrypted connection when no valid CA is available (e.g. mis-set env on Render)."""
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    return {"ssl": ctx}


def _build_mysql_ssl_options() -> dict:
    """Aiven MySQL requires SSL; prefer verifying with the service CA certificate."""
    if _env("DB_SSL", "false").lower() not in ("1", "true", "yes"):
        return {}

    ca_pem = _env("DB_SSL_CA_PEM", "")
    if ca_pem and _pem_is_usable(ca_pem):
        return {"ssl": _ssl_context_from_pem(ca_pem)}

    ca_path = _env("DB_SSL_CA", "")
    if ca_path:
        path = Path(ca_path)
        if not path.is_absolute():
            path = BASE_DIR / path
        if text := _read_pem_file(path):
            if _pem_is_usable(text):
                return {"ssl": _ssl_context_from_pem(text)}

    default_ca = BASE_DIR / "certs" / "ca.pem"
    if text := _read_pem_file(default_ca):
        if _pem_is_usable(text):
            return {"ssl": _ssl_context_from_pem(text)}

    return _ssl_options_without_verification()


_db_options = _build_mysql_ssl_options()

if _env('USE_SQLITE', 'False').lower() == 'true' or not _env('DB_NAME', ''):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': _env('DB_NAME', 'restaurant_db'),
            'USER': _env('DB_USER', 'root'),
            'PASSWORD': _env('DB_PASSWORD', 'newpassword'),
            'HOST': _env('DB_HOST', 'localhost'),
            'PORT': _env('DB_PORT', '3306'),
            **({'OPTIONS': _db_options} if _db_options else {}),
        }
    }

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
}

# Simple JWT Configuration
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# CORS — allow Vercel frontend (no trailing slash on origins)
_default_cors = "https://tabletop-restaurant.vercel.app"
_cors_raw = _env("CORS_ALLOWED_ORIGINS", _default_cors)
_cors_origins = list(
    dict.fromkeys(o.strip().rstrip("/") for o in _cors_raw.split(",") if o.strip())
)
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = _cors_origins
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://[\w-]+\.vercel\.app$",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CSRF_TRUSTED_ORIGINS = _cors_origins.copy()

# Media files (Cloudinary for persistence on Render)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': _env('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': _env('CLOUDINARY_API_KEY'),
    'API_SECRET': _env('CLOUDINARY_API_SECRET'),
}

MEDIA_URL = '/media/'
# MEDIA_ROOT is not strictly needed for Cloudinary but kept for local fallback
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Compatibility for libraries that still check old settings
STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Email OTP authentication
EMAIL_HOST = _env("EMAIL_HOST")
EMAIL_PORT = int(_env("EMAIL_PORT", "587"))
EMAIL_HOST_USER = _env("EMAIL_HOST_USER")
# Gmail app passwords are often shown with spaces — remove them
EMAIL_HOST_PASSWORD = _env("EMAIL_HOST_PASSWORD").replace(" ", "")
EMAIL_USE_TLS = _env("EMAIL_USE_TLS", "True").lower() in ("1", "true", "yes")
EMAIL_USE_SSL = _env("EMAIL_USE_SSL", "False").lower() in ("1", "true", "yes")
if EMAIL_PORT == 465:
    EMAIL_USE_TLS = False
    EMAIL_USE_SSL = True
EMAIL_TIMEOUT = int(_env("EMAIL_TIMEOUT", "25"))
# Gmail requires FROM to match the authenticated account (plain address works best)
DEFAULT_FROM_EMAIL = _env("DEFAULT_FROM_EMAIL", "") or EMAIL_HOST_USER or "noreply@sridurgahotel.local"

# Resend API (Preferred for Render to bypass SMTP blocks)
RESEND_API_KEY = _env("RESEND_API_KEY")

if RESEND_API_KEY:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    EMAIL_OTP_DELIVERY = "resend"
elif EMAIL_HOST and EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_OTP_DELIVERY = "smtp"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    EMAIL_OTP_DELIVERY = "console"

# Set OTP_SHOW_IN_API=true only for local debugging without real email
OTP_SHOW_IN_API = _env("OTP_SHOW_IN_API", "false").lower() in ("1", "true", "yes")
OTP_LENGTH = 6
OTP_EXPIRY_MINUTES = 10
OTP_RESEND_SECONDS = 60
