# Generated by manually on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_is_guest_alter_order_id_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
