# Generated by Django 5.2.7 on 2026-05-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_fooditem_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sri Durga Military Hotel', max_length=200)),
                ('packing_charge', models.DecimalField(decimal_places=2, default=20.0, max_digits=8)),
                ('delivery_charge_info', models.CharField(default='Delivery charges depend on distance', max_length=255)),
                ('bulk_order_info', models.CharField(default='Bulk order available (6hrs advance booking)', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
