# Generated by Django 5.2.7 on 2026-05-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_restaurantconfig_alter_category_id_alter_fooditem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
