# Generated by Django 6.0.5 on 2026-05-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_category_id_alter_fooditem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantconfig',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
