# Generated by Django 5.2.7 on 2026-05-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_restaurantconfig_gst_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='current_stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='default_stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='weekday_stock',
            field=models.JSONField(blank=True, default=dict, help_text="Stock per weekday (e.g., {'Mon': 10, 'Sun': 20})"),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='closing_time',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='opening_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='weekday_timing',
            field=models.JSONField(blank=True, default=dict, help_text="Opening/closing per weekday (e.g., {'Mon': {'open': '09:00', 'close': '22:00'}})"),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restaurantconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
