# Generated by Django 6.0.5 on 2026-05-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_category_id_alter_fooditem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantconfig',
            name='last_report_generated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='last_stock_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
