# Generated by manually on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_id_alter_emailotp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('user', 'User'), ('guest', 'Guest')], default='user', max_length=20),
        ),
    ]
