# Generated by Django 6.0.5 on 2026-05-22 04:03

import accounts.models
from django.db import migrations, models

def deduplicate_emails(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    # Find emails that appear more than once
    duplicate_emails = CustomUser.objects.values('email').annotate(email_count=models.Count('id')).filter(email_count__gt=1)
    
    for entry in duplicate_emails:
        email = entry['email']
        if not email:
            continue
        # Keep the most recently logged in user, or the oldest account if never logged in
        users = list(CustomUser.objects.filter(email=email).order_by('-last_login', '-date_joined'))
        # Keep the first one, delete the rest
        for user in users[1:]:
            user.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_id_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.RunPython(deduplicate_emails, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_/spaces only.', max_length=150, validators=[accounts.models.SpaceUnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
